-- ErgoCare+ : ALL PENDING MIGRATIONS (paste this whole file into the Supabase dashboard SQL editor and Run once)
-- Generated 2026-07-04. Safe to re-run: statements are idempotent.

-- 1) Let patients delete their own generated reports (recommendations).
--    A recommendation belongs to the patient whose assessment produced it.
drop policy if exists "recommendations_delete_patient" on public.recommendations;
create policy "recommendations_delete_patient" on public.recommendations
  for delete using (
    exists (
      select 1 from public.assessments a
      where a.id = recommendations.assessment_id
        and a.patient_user_id::text = auth.uid()::text
    )
  );

-- 2) Landing-page stats: count real generated programs.
--    Programs generated by the AI are stored in `recommendations`;
--    the old `exercise_programs` table is legacy and stays empty, so the
--    landing page was showing the wrong number.
CREATE OR REPLACE FUNCTION public.get_platform_stats()
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  patient_count      integer;
  physio_count       integer;
  assessment_count   integer;
  program_count      integer;
BEGIN
  SELECT COUNT(*) INTO patient_count
    FROM user_roles WHERE role = 'patient';

  SELECT COUNT(*) INTO physio_count
    FROM user_roles WHERE role = 'physiotherapist';

  SELECT COUNT(*) INTO assessment_count
    FROM assessments;

  SELECT COUNT(*) INTO program_count
    FROM recommendations;

  RETURN json_build_object(
    'patients',         patient_count,
    'physiotherapists', physio_count,
    'assessments',      assessment_count,
    'programs',         program_count
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_platform_stats() TO anon;
GRANT EXECUTE ON FUNCTION public.get_platform_stats() TO authenticated;

-- International-standard patient-reported outcome measures for progress_entries.
--
-- pain_level stays as the NPRS (0-10). New columns:
--   function_score  : PSFS-style main-activity ability, 0-10 (higher = better)
--   sessions_done   : exercise sessions completed this week (count)
--   sessions_target : prescribed weekly session target at time of entry
--   groc            : Global Rating of Change, -7..+7 (Jaeschke 15-point)
--   ears_score      : Exercise Adherence Rating Scale total, 0-24 (higher = better)
--   ears_answers    : raw per-item EARS responses for clinician review
--
-- energy_level / adherence remain for old entries (legacy display only).

alter table public.progress_entries
  add column if not exists function_score integer,
  add column if not exists sessions_done integer,
  add column if not exists sessions_target integer,
  add column if not exists groc integer,
  add column if not exists ears_score integer,
  add column if not exists ears_answers jsonb;

-- ============================================================================
-- 1) Prevent double-booking: one active appointment per physio per slot.
-- ============================================================================
create unique index if not exists uniq_active_appointment_slot
  on public.appointments (physiotherapist_id, appointment_date, appointment_time)
  where status <> 'cancelled';

-- Patients can only SELECT their own appointments under RLS, so the booking
-- page needs a definer function to learn which slots are already taken.
-- It intentionally returns times only - no patient data leaks.
create or replace function public.get_booked_slots(p_physio uuid, p_date date)
returns setof time
language sql
security definer
set search_path = public
as $$
  select appointment_time
  from appointments
  where physiotherapist_id = p_physio
    and appointment_date = p_date
    and status <> 'cancelled';
$$;

grant execute on function public.get_booked_slots(uuid, date) to authenticated;

-- ============================================================================
-- 2) In-app notifications.
-- ============================================================================
create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,            -- auth user id of the recipient
  type text not null,               -- booking_request | booking_confirmed | booking_cancelled | booking_completed | message
  data jsonb,
  link text,
  created_at timestamptz default now(),
  read_at timestamptz
);

create index if not exists idx_notifications_user_unread
  on public.notifications (user_id, read_at, created_at desc);

alter table public.notifications enable row level security;

drop policy if exists "notifications_select_own" on public.notifications;
create policy "notifications_select_own" on public.notifications
  for select using (user_id = auth.uid()::text);

drop policy if exists "notifications_update_own" on public.notifications;
create policy "notifications_update_own" on public.notifications
  for update using (user_id = auth.uid()::text);

-- New booking -> notify the physiotherapist.
create or replace function public.notify_new_booking()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  physio_user text;
  patient_name text;
begin
  select p.user_id::text into physio_user from profiles p where p.id = new.physiotherapist_id;
  select nullif(trim(coalesce(pp.first_name, '') || ' ' || coalesce(pp.last_name, '')), '')
    into patient_name from profiles pp where pp.id = new.patient_id;
  if physio_user is not null then
    insert into notifications (user_id, type, data, link)
    values (
      physio_user,
      'booking_request',
      jsonb_build_object('date', new.appointment_date, 'time', new.appointment_time, 'patient', patient_name),
      '/physio-sessions'
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_notify_new_booking on public.appointments;
create trigger trg_notify_new_booking
  after insert on public.appointments
  for each row execute function public.notify_new_booking();

-- Status change -> notify the patient.
create or replace function public.notify_booking_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  patient_user text;
begin
  if new.status is distinct from old.status
     and new.status in ('confirmed', 'cancelled', 'completed') then
    select p.user_id::text into patient_user from profiles p where p.id = new.patient_id;
    if patient_user is not null then
      insert into notifications (user_id, type, data, link)
      values (
        patient_user,
        'booking_' || new.status,
        jsonb_build_object('date', new.appointment_date, 'time', new.appointment_time),
        '/booking'
      );
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_notify_booking_status on public.appointments;
create trigger trg_notify_booking_status
  after update on public.appointments
  for each row execute function public.notify_booking_status();

-- New message -> notify the other participant.
create or replace function public.notify_new_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  conv record;
  recipient_profile uuid;
  recipient_user text;
begin
  select patient_id, physiotherapist_id into conv
  from conversations where id = new.conversation_id;
  if conv is null then return new; end if;
  if conv.patient_id = new.sender_id then
    recipient_profile := conv.physiotherapist_id;
  else
    recipient_profile := conv.patient_id;
  end if;
  select user_id::text into recipient_user from profiles where id = recipient_profile;
  if recipient_user is not null then
    insert into notifications (user_id, type, data, link)
    values (recipient_user, 'message', jsonb_build_object('preview', left(new.content, 80)), '/messages');
  end if;
  return new;
end;
$$;

drop trigger if exists trg_notify_new_message on public.messages;
create trigger trg_notify_new_message
  after insert on public.messages
  for each row execute function public.notify_new_message();

-- ============================================================================
-- 3) Realtime: push new messages and notifications to connected clients.
-- ============================================================================
do $$ begin
  alter publication supabase_realtime add table public.messages;
exception when duplicate_object then null; end $$;

do $$ begin
  alter publication supabase_realtime add table public.notifications;
exception when duplicate_object then null; end $$;
-- ============================================================================
-- 1) Physiotherapist verification.
--
-- Previously the "Verified Physiotherapist" badge showed for ANY account
-- with the physiotherapist role, with no actual credential check. This adds
-- a real license number captured at signup and a verification flag that
-- only the platform operator sets (there is no in-app admin UI yet, so
-- verify by running, per physiotherapist, once their license is checked:
--   update public.profiles set verified_at = now(), verified_by = 'admin'
--   where user_id = '<their auth user id>';
-- ============================================================================
alter table public.profiles
  add column if not exists license_number text,
  add column if not exists verified_at timestamptz,
  add column if not exists verified_by text;

-- ============================================================================
-- 2) One-time telehealth consent per patient, captured before their first
--    video/phone session, since Tanzania has no finalized telehealth-consent
--    regulation yet - this is a self-imposed safeguard.
-- ============================================================================
alter table public.profiles
  add column if not exists telehealth_consent_at timestamptz;
