-- 1) Let patients delete their own generated reports (recommendations).
--    A recommendation belongs to the patient whose assessment produced it.
drop policy if exists "recommendations_delete_patient" on public.recommendations;
create policy "recommendations_delete_patient" on public.recommendations
  for delete using (
    exists (
      select 1 from public.assessments a
      where a.id = recommendations.assessment_id
        and a.patient_user_id::text = auth.uid()::text
    )
  );

-- 2) Landing-page stats: count real generated programs.
--    Programs generated by the AI are stored in `recommendations`;
--    the old `exercise_programs` table is legacy and stays empty, so the
--    landing page was showing the wrong number.
CREATE OR REPLACE FUNCTION public.get_platform_stats()
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  patient_count      integer;
  physio_count       integer;
  assessment_count   integer;
  program_count      integer;
BEGIN
  SELECT COUNT(*) INTO patient_count
    FROM user_roles WHERE role = 'patient';

  SELECT COUNT(*) INTO physio_count
    FROM user_roles WHERE role = 'physiotherapist';

  SELECT COUNT(*) INTO assessment_count
    FROM assessments;

  SELECT COUNT(*) INTO program_count
    FROM recommendations;

  RETURN json_build_object(
    'patients',         patient_count,
    'physiotherapists', physio_count,
    'assessments',      assessment_count,
    'programs',         program_count
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_platform_stats() TO anon;
GRANT EXECUTE ON FUNCTION public.get_platform_stats() TO authenticated;
